export const REGISTER_TRY = "REGISTER_TRY";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_TRY = "LOGIN_TRY";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const FIND_TOKEN = "FIND_TOKEN";

export const GET_BOOKS_TRY = "GET_BOOKS_TRY";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAIL = "GET_BOOKS_FAIL";

export const GET_SINGLE_TRY = "GET_SINGLE_TRY";
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS";
export const GET_SINGLE_FAIL = "GET_SINGLE_FAIL";

export const POST_REVIEW_TRY = "POST_REVIEW_TRY";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAIL = "POST_REVIEW_FAIL";

export const DELETE_REVIEW_TRY = "DELETE_REVIEW_TRY";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const UPDATE_REVIEW_TRY = "UPDATE_REVIEW_TRY";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAIL = "UPDATE_REVIEW_FAIL";